[supervisord]
nodaemon=true

[program:backend]
directory=/backend
command=node index.js
autostart=true
autorestart=true
environment=PORT=4001,ALLOWED_ORIGIN=http://localhost:3001,CODE_RUNNER_USE_DOCKER=false,PYTHON_BIN=python3

[program:frontend]
directory=/frontend
command=serve -s . -l 3001 --single
autostart=true
autorestart=true
